name: Build and Release

on:
  push:
    branches:
      - '**' # Triggers the workflow on any branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.30.0'

      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: cmake --build build --config Debug

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: build/*.zip
